Ext.define('HowToApply.model.Pets', {
			extend: 'Ext.data.Model',
			config: {
        	fields: [ 
        	   	{name: 'pets[0].Type',  type: 'string'}, 
        	   	{name: 'pets[0].DogWeight',  type: 'string'},
        	   	{name: 'pets[0].SpecifyType',  type: 'string'},
        	   	{name: 'pets[1].Type',  type: 'string'}, 
        	   	{name: 'pets[1].DogWeight',  type: 'string'},
        	   	{name: 'pets[1].SpecifyType',  type: 'string'},
        	   	{name: 'pets[2].Type',  type: 'string'}, 
        	   	{name: 'pets[2].DogWeight',  type: 'string'},
        	   	{name: 'pets[2].SpecifyType',  type: 'string'},
        	   	{name: 'pets[3].Type',  type: 'string'}, 
        	   	{name: 'pets[3].DogWeight',  type: 'string'},
        	   	{name: 'pets[3].SpecifyType',  type: 'string'},
        	   	{name: 'pets[4].Type',  type: 'string'}, 
        	   	{name: 'pets[4].DogWeight',  type: 'string'},
        	   	{name: 'pets[4].SpecifyType',  type: 'string'},
        	   	{name: 'pets[5].Type',  type: 'string'}, 
        	   	{name: 'pets[5].DogWeight',  type: 'string'},
        	   	{name: 'pets[5].SpecifyType',  type: 'string'},
        	   	{name: 'pets[6].Type',  type: 'string'}, 
        	   	{name: 'pets[6].DogWeight',  type: 'string'},
        	   	{name: 'pets[6].SpecifyType',  type: 'string'},
        	   	{name: 'pets[7].Type',  type: 'string'}, 
        	   	{name: 'pets[7].DogWeight',  type: 'string'},
        	   	{name: 'pets[7].SpecifyType',  type: 'string'},
        	   	{name: 'pets[8].Type',  type: 'string'}, 
        	   	{name: 'pets[8].DogWeight',  type: 'string'},
        	   	{name: 'pets[8].SpecifyType',  type: 'string'},
        	   	{name: 'pets[9].Type',  type: 'string'}, 
        	   	{name: 'pets[9].DogWeight',  type: 'string'},
        	   	{name: 'pets[9].SpecifyType',  type: 'string'},
      ]
    }
});


var pets_model = Ext.create('HowToApply.model.Kin',{
		'pets[0].Type':'',
		'pets[0].DogWeight':'',	
		'pets[0].SpecifyType':'',	
		'pets[1].Type':'',
		'pets[1].DogWeight':'',	
		'pets[1].SpecifyType':'',
		'pets[2].Type':'',
		'pets[2].DogWeight':'',	
		'pets[2].SpecifyType':'',
		'pets[3].Type':'',
		'pets[3].DogWeight':'',	
		'pets[3].SpecifyType':'',
		'pets[4].Type':'',
		'pets[4].DogWeight':'',	
		'pets[4].SpecifyType':'',
		'pets[5].Type':'',
		'pets[5].DogWeight':'',	
		'pets[5].SpecifyType':'',
		'pets[6].Type':'',
		'pets[6].DogWeight':'',	
		'pets[6].SpecifyType':'',
		'pets[7].Type':'',
		'pets[7].DogWeight':'',	
		'pets[7].SpecifyType':'',
		'pets[8].Type':'',
		'pets[8].DogWeight':'',	
		'pets[8].SpecifyType':'',
		'pets[9].Type':'',
		'pets[9].DogWeight':'',	
		'pets[9].SpecifyType':'',
})